### ISSUE TITLE
issue: TypeError: updateFormState is not a function error when using "@hookform/devtools": "^4.3.1".

### ISSUE THREAD

**Issue by mmalone-tongal** [react-hook-form/react-hook-form#10417]
### Version Number

7.41.5

### Codesandbox/Expo snack

https://codesandbox.io/s/eager-sun-jt4df

### Steps to reproduce

1. Install "@hookform/devtools": "^4.3.1".
2. Install "react-hook-form": "^7.41.5",
3. Create a form  and enable the devtool

![devtool-error](https://github.com/react-hook-form/react-hook-form/assets/56611065/a9952c00-b919-4212-833a-1024d049e6b5)

### Expected behaviour

We should be able to use the devtool without triggering an error

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Relevant log output

```shell
Uncaught (in promise) TypeError: updateFormState is not a function
    at shouldRenderFormState (index.cjs.development.js:194:1)
    at Object.next (index.cjs.development.js:278:1)
    at Object.next (index.esm.mjs:1158:1)
    at Object.onChange (index.esm.mjs:1782:1)
    at index.esm.mjs:412:38
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4070:1)
    at executeDispatch (react-dom.development.js:8243:1)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
Please upgrade to the latest.

**Comment by mmalone-tongal** [comment]
We did but we got a few build errors with the new version.  We'll look on our end for a solution to that.
