### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by iget-master** [react-hook-form/react-hook-form#10421]
### Version Number

1111

### Codesandbox/Expo snack

2222

### Steps to reproduce

Access https://react-hook-form.com/ and see that the website is down

### Expected behaviour

It should work :-D

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Uncaught (in promise) ChunkLoadError: Loading chunk 6691 failed.
(error: https://react-hook-form.com/component---src-pages-index-tsx-319741915e1e59df4402.js)
    at Object.j (webpack-runtime-37ce9cab243ae0f428fc.js:1:7333)
    at webpack-runtime-37ce9cab243ae0f428fc.js:1:855
    at Array.reduce (<anonymous>)
    at Function.e (webpack-runtime-37ce9cab243ae0f428fc.js:1:820)
    at component---src-pages-index-tsx (app-73e9b71e4d585bc87989.js:2:49292)
    at t.loadComponent (app-73e9b71e4d585bc87989.js:2:70982)
    at app-73e9b71e4d585bc87989.js:2:66145
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Try again? Looks fine to me
