### ISSUE TITLE
issue: Unable to find form context in monorepo

### ISSUE THREAD

**Issue by WingsDevelopment** [react-hook-form/react-hook-form#10483]
### Version Number

^7.44.2

### Codesandbox/Expo snack

https://github.com/WingsDevelopment/pnpm-monorepo-repeat-fwb

### Steps to reproduce

Clone repository, follow the readme instructions,
build shared ui library,
start aplication.

### Expected behaviour

Expected behaviour is to find form context with useFormContext inside my SharedTextField

### Relevant log output

```shell
Uncaught runtime errors:
×
ERROR
Cannot read properties of null (reading 'control')
TypeError: Cannot read properties of null (reading 'control')
    at SharedTextField (http://localhost:3001/static/js/bundle.js:108924:56)
    at renderWithHooks (http://localhost:3001/static/js/bundle.js:85618:22)
    at mountIndeterminateComponent (http://localhost:3001/static/js/bundle.js:88904:17)
    at beginWork (http://localhost:3001/static/js/bundle.js:90200:20)
    at HTMLUnknownElement.callCallback (http://localhost:3001/static/js/bundle.js:75210:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3001/static/js/bundle.js:75254:20)
    at invokeGuardedCallback (http://localhost:3001/static/js/bundle.js:75311:35)
    at beginWork$1 (http://localhost:3001/static/js/bundle.js:95185:11)
    at performUnitOfWork (http://localhost:3001/static/js/bundle.js:94432:16)
    at workLoopSync (http://localhost:3001/static/js/bundle.js:94355:9)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
why is this issue report to us?

**Comment by WingsDevelopment** [comment]
Where should I report this issue then? @bluebill1049

Thanks @despin but adding FormProvider didn't help, I was trying with that before aswell, but after I played around I forgot to put it back, however, new version of code is on git now with FormProvider  still not working..

I am also trying to understand why...?
