### ISSUE TITLE
issue: unable to SSR useFormContext in next.js

### ISSUE THREAD

**Issue by neotrow** [react-hook-form/react-hook-form#10840]
### Version Number

7.45.4

### Codesandbox/Expo snack

https://github.com/neotrow/useFormContext-issue

### Steps to reproduce

Hope it's okay that I put in a github link instead of a codesandbox. 

1. run `yarn` to install all packages
2. run `yarn build` 

### Expected behaviour

I would expect `useFormContext` to not be null on the server side / during the static pages generator. 

They same issue appears if you use getServerSideProps.  

### Relevant log output

```shell
$ yarn build
yarn run v1.22.19
$ next build
- info Linting and checking validity of types
- info Creating an optimized production build
- info Compiled successfully
- info Collecting page data
[    ] - info Generating static pages (0/3)undefined
TypeError: Cannot destructure property 'register' of '(0 , react_hook_form__WEBPACK_IMPORTED_MODULE_2__.useFormContext)(...)' as it is null.
    at NestedInput (C:\Users\user\Desktop\temp\my-app\.next\server\pages\index.js:143:13)
    at Wc (C:\Users\user\Desktop\temp\my-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:68:44)
    at Zc (C:\Users\user\Desktop\temp\my-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:253)
    at Z (C:\Users\user\Desktop\temp\my-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at $c (C:\Users\user\Desktop\temp\my-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:78:98)
    at bd (C:\Users\user\Desktop\temp\my-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:77:404)
    at Z (C:\Users\user\Desktop\temp\my-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:217)
    at $c (C:\Users\user\Desktop\temp\my-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:78:98)
    at Zc (C:\Users\user\Desktop\temp\my-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:71:145)
    at Z (C:\Users\user\Desktop\temp\my-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot destructure property 'register' of '(0 , react_hook_form__WEBPACK_IMPORTED_MODULE_2__.useFormContext)(...)' as it is null.
    at NestedInput (C:\Users\user\Desktop\temp\my-app\.next\server\pages\index.js:143:13)
    at Wc (C:\Users\user\Desktop\temp\my-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:68:44)
    at Zc (C:\Users\user\Desktop\temp\my-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:70:253)
    at Z (C:\Users\user\Desktop\temp\my-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
    at $c (C:\Users\user\Desktop\temp\my-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:78:98)
    at bd (C:\Users\user\Desktop\temp\my-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:77:404)
    at Z (C:\Users\user\Desktop\temp\my-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:217)
    at $c (C:\Users\user\Desktop\temp\my-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:78:98)
    at Zc (C:\Users\user\Desktop\temp\my-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:71:145)
    at Z (C:\Users\user\Desktop\temp\my-app\node_modules\react-dom\cjs\react-dom-server.browser.production.min.js:76:89)
- info Generating static pages (3/3)

> Export encountered errors on following paths:
        /
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
I believe it's a duplicate of #3894

**Comment by neotrow** [comment]
@Moshyfawn 

I would disagree. Because the issue https://github.com/orgs/react-hook-form/discussions/3894 is about creating a package that uses `react-hook-form`. But my example is only using `react-hook-form`. 

Maybe it's related but not the same issue IMO.

**Comment by Moshyfawn** [comment]
> @Moshyfawn
> 
> I would disagree. Because the issue https://github.com/orgs/react-hook-form/discussions/3894 is about creating a package that uses `react-hook-form`. But my example is only using `react-hook-form`.
> 
> Maybe it's related but not the same issue IMO.

Fair, my bad! I've schemed though #3894 and found a mention of Next.js without reading too much into it

**Comment by bluebill1049** [comment]
Can you recreate with just a normal react context? There is nothing special with FormProivder as it just uses react's API.

**Comment by neotrow** [comment]
@bluebill1049 

I will try that, thanks for the input.

**Comment by IMPERIAL-HEX** [comment]
If you have your form directly on the next page try making a component of that form and from there point onwards use form context provider and access your nested components or form in that component. 
The problem is that next js page can't access any context in general because a page is rendered on server and components on client.
As far as I've seen this goes myself any context value shows undefined when consoling on page but shows data inside components.

**Comment by neotrow** [comment]
@IMPERIAL-HEX 

Didn't work for me, this is what you meant right? 
https://github.com/neotrow/useFormContext-issue/blob/feature/inner-component/pages/index.tsx

@bluebill1049 

Normal react contexts work just fine:
https://github.com/neotrow/useFormContext-issue/blob/feature/normal-context/pages/index.tsx


I think the issue is that the client and server build use different versions of the `react-hook-form` library? 
I assume that the client uses module version and the server common js? 
But than I don't understand how this causes an issue since it should behave the same way for the `react` library itself and than it should also not work for that....

Any ideas or leads?

**Comment by IMPERIAL-HEX** [comment]
@neotrow 
For now in your inner component. I am not seeing any FormProvider wrapper on your form.
Rest i am not sure for what else to try.

```typescript
FormProvider {...methods}>
      // pass all methods into the context
      <form onSubmit={methods.handleSubmit(onSubmit)}>
        <NestedInput />
        <input type="submit" />
      </form>
    </FormProvider>
```

**Comment by neotrow** [comment]
@IMPERIAL-HEX 

Of course,  you are right..  🤦
I forgot the `FormProvider` completley...

Case closed, many thx!
