### ISSUE TITLE
issue: homepage is down

### ISSUE THREAD

**Issue by cellog** [react-hook-form/react-hook-form#11604]
### Version Number

n/a

### Codesandbox/Expo snack

n/a

### Steps to reproduce

1. Go to https://react-hook-form.com/

### Expected behaviour

site loads

### Relevant log output

```shell
/c336cd55610b29370c360729bf8d09d13f5f3af8-ef60b92637b2a1febe82.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
app-a274cb24ab47115ba831.js:2 page resources for / not found. Not rendering React
(anonymous) @ app-a274cb24ab47115ba831.js:2
/24dea1732e3205afc99743970091eff17910cfaa-73ff2b65e970c492c3a5.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
webpack-runtime-b4e3d9bf4d61a8d791a3.js:1 Uncaught (in promise) ChunkLoadError: Loading chunk 8602 failed.
(error: https://react-hook-form.com/c336cd55610b29370c360729bf8d09d13f5f3af8-ef60b92637b2a1febe82.js)
    at s.f.j (webpack-runtime-b4e3d9bf4d61a8d791a3.js:1:6997)
    at webpack-runtime-b4e3d9bf4d61a8d791a3.js:1:855
    at Array.reduce (<anonymous>)
    at s.e (webpack-runtime-b4e3d9bf4d61a8d791a3.js:1:820)
    at component---src-pages-index-tsx (app-a274cb24ab47115ba831.js:2:36420)
    at t.loadComponent (app-a274cb24ab47115ba831.js:2:51600)
    at app-a274cb24ab47115ba831.js:2:47295
/icons/icon-144x144.png?v=33dbda822526f0cf9f02a335ee65d925:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
react-hook-form.com/:1 Error while trying to use the following icon from the Manifest: https://react-hook-form.com/icons/icon-144x144.png?v=33dbda822526f0cf9f02a335ee65d925 (Download error or resource isn't a valid image)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Moshyfawn** [comment]
Seems fine on my end
<img width="1554" alt="image" src="https://github.com/react-hook-form/react-hook-form/assets/16290753/e4a8a5af-47e2-48cf-86ff-83a55c3aefde">

**Comment by Moshyfawn** [comment]
Looks like #10469

**Comment by bluebill1049** [comment]
gatsby cache related.
