### ISSUE TITLE
issue: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /app/node_modules/react-hook-form/dist/index.cjs.js

### ISSUE THREAD

**Issue by Navaneethkrish** [react-hook-form/react-hook-form#7113]
### Version Number

7.20.2

### Codesandbox/Expo snack

https://www.npmjs.com/package/react-hook-form

### Steps to reproduce

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /app/node_modules/react-hook-form/dist/index.cjs.js
require() of ES modules is not supported.
require() of /app/node_modules/react-hook-form/dist/index.cjs.js from /app/.next/server/pages/user/sign-in/symbol.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.cjs.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /app/node_modules/react-hook-form/package.json.
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1089:13)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.BTiB (/app/.next/server/pages/user/sign-in/symbol.js:429:18)
    at __webpack_require__ (/app/.next/server/pages/user/sign-in/symbol.js:29:31)
    at Object.e6Nh (/app/.next/server/pages/user/sign-in/symbol.js:1922:73)
    at __webpack_require__ (/app/.next/server/pages/user/sign-in/symbol.js:29:31)
    at Module.Wt1M (/app/.next/server/pages/user/sign-in/symbol.js:965:21) {
  code: 'ERR_REQUIRE_ESM'

Getting this error at run time after upgrading to the latest version of 7.20.2

### Expected behaviour

Application should work fine

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Edge

### Relevant log output

```shell
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /app/node_modules/react-hook-form/dist/index.cjs.js
require() of ES modules is not supported.
require() of /app/node_modules/react-hook-form/dist/index.cjs.js from /app/.next/server/pages/user/sign-in/symbol.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.cjs.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /app/node_modules/react-hook-form/package.json.
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1089:13)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.BTiB (/app/.next/server/pages/user/sign-in/symbol.js:429:18)
    at __webpack_require__ (/app/.next/server/pages/user/sign-in/symbol.js:29:31)
    at Object.e6Nh (/app/.next/server/pages/user/sign-in/symbol.js:1922:73)
    at __webpack_require__ (/app/.next/server/pages/user/sign-in/symbol.js:29:31)
    at Module.Wt1M (/app/.next/server/pages/user/sign-in/symbol.js:965:21) {
  code: 'ERR_REQUIRE_ESM'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/resolvers/issues/271

**Comment by bluebill1049** [comment]
looks like this is not related to resolver, provide a codesandbox or reproduceable repo.
