### ISSUE TITLE
issue: using `nodeName` as the Controller name results in `elem.nodeName.toLowerCase is not a function`

### ISSUE THREAD

**Issue by andydotph** [react-hook-form/react-hook-form#9127]
### Version Number

7.36.1

### Codesandbox/Expo snack

https://codesandbox.io/s/trusting-bhaskara-6rf712

### Steps to reproduce

1. Go to sandbox
2. Hover mouse between input text box and button
3. See error

### Expected behaviour

No errors should be encountered.

If `nodeName` is changed to different name like `customNodeName` for lines 53, 60, 69, and 75, the issue goes away.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Uncaught TypeError: elem.nodeName.toLowerCase is not a function
    at shouldUseChangeEvent (react-dom.development.js:7786:1)
    at extractEvents$1 (react-dom.development.js:7967:1)
    at extractEvents$5 (react-dom.development.js:9025:1)
    at dispatchEventsForPlugins (react-dom.development.js:9096:1)
    at react-dom.development.js:9288:1
    at batchedUpdates$1 (react-dom.development.js:26140:1)
    at batchedUpdates (react-dom.development.js:3991:1)
    at dispatchEventForPluginEventSystem (react-dom.development.js:9287:1)
    at dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay (react-dom.development.js:6465:1)
    at dispatchEvent (react-dom.development.js:6457:1)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
![Screen Shot 2022-10-03 at 7 53 26 pm](https://user-images.githubusercontent.com/10513364/193537963-b4cf7b16-9322-4e8e-9461-3419b2ca6f8c.png)

please refer to the stack trace, not related to this library.

**Comment by andydotph** [comment]
thanks @bluebill1049, 

react-final-form is also affected by this: https://github.com/final-form/react-final-form/issues/871

and after some more digging, I found this on `react`'s github repo which goes back to 2016: https://github.com/facebook/react/issues/6284

Apologies for the invalid bug report.

**Comment by bluebill1049** [comment]
all good. thanks for the update.
